### ISSUE TITLE
Incorrect page when jumping back chapters

### ISSUE THREAD

**Issue by jvllmr** [luigi311/tanoshi#22]
When using v0.33.0 via ghcr.io/luigi311/tanoshi:latest docker container image, tanoshi jumps to the last page of the chapter I jumped from when switching to previous chapters. I.e. tanoshi jumps to slide 23 in  chapter 32 if chapter 33 has 23 slides. This happens even if chapter 32 doesnt't have 23 slides. I couldn't find out yet if this is connected to the extensions I am using tho. I use the builds from the 1.79.0 branch. I also had this issue with earlier builds of the extensions with older versions of tanoshi/-extension builds from this repository, but I never noticed it when I was using the original faldez/tanoshi builds.

**Comment by luigi311** [comment]
This has always been an issue from what ive seen. Im not sure why it jumps to everything but the actual last page of the previous chapter when going back a chapter. Its something i need to look at but its not been a huge issue and i havent had time to learn more rust/html to figure this out.

**Comment by jvllmr** [comment]
No stress. It never really bothered me a lot. Just took the time to document this while upgrading my infrastructure. I might take a look into the issue myself if I have a time.

**Comment by luigi311** [comment]
I think i found the issue, can you test the main branch and see if that fixes it for you? Looks like pages wasnt  being updated with the new amount

**Comment by jvllmr** [comment]
I temporarily switched to the main tag and it seems to work now. Thanks!
